### ISSUE TITLE
设计借鉴

### ISSUE THREAD

**Issue by wtlyu** [QSCTech/freshman#53]
您好，我们正在设计一个迎新网站，看到了贵社的设计非常欣赏。现在我们所做的初步效果已经可以看到，设计上比较大地参考了贵社的设计，但并没有使用或参考贵社的代码（即仅外观上比较相似）。出于礼貌和避免不必要 的纠纷，希望能够得到贵方的认可和同意。

附工程截图效果
![image](https://cloud.githubusercontent.com/assets/8267138/16981835/1b076584-4e9f-11e6-8f34-341dc82cf526.png)

上海科技大学 学生GeekPie社团

**Comment by wtlyu** [comment]
https://zone.geekpie.org/

**Comment by Senorsen** [comment]
@YorkHe @zenozeng @alejwong

**Comment by YorkHe** [comment]
@eastpiger  Sorry 刚看见。 我们很欢迎与其他学校进行友好的交流。

关于设计的问题， 出于尊重设计师工作成果的考虑， 希望能够在比较显眼的地方放置一个设计参考的链接， 然后链接到https://f.zjuqsc.com 。 如首页左下方的Copyright区域就好。 

如： [设计参考：浙江大学新生手册](f.zjuqsc.com)

**Comment by wtlyu** [comment]
@YorkHe 之前没收到回复，我们先行在这里添加了鸣谢标志 https://zone.geekpie.org/%E7%89%B9%E5%85%B8/%E5%85%B3%E4%BA%8E
您看能否接受？

**Comment by YorkHe** [comment]
@eastpiger 在那一个小小的角落放一个Acknowledgement有点意义不明。

如果可以的话， 还是按照我们提出的办法来做吧。
